# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Base": "00_base.ipynb",
         "modify_cmd": "00_base.ipynb",
         "Fastp": "01_fastp.ipynb",
         "Fastqc": "02_fastqc.ipynb",
         "Star": "03_star.ipynb",
         "Hisat2": "04_hisat2.ipynb",
         "Samtools": "05_samtools.ipynb",
         "Stringtie": "06_stringtie.ipynb",
         "Featurecounts": "07_featurecounts.ipynb",
         "Inhouerscript": "08_inhouse_rscript.ipynb",
         "Bitk": "09_bitk.ipynb",
         "Rnasamba": "10_rnasamba.ipynb",
         "Gffread": "11_gffread.ipynb",
         "Minimap2": "12_minimap2.ipynb",
         "Gffcompare": "13_gffcompare.ipynb",
         "load_config": "utils.ipynb",
         "config": "utils.ipynb"}

modules = ["softwares/base.py",
           "softwares/fastq/fastp.py",
           "softwares/fastq/fastqc.py",
           "softwares/fastq/star.py",
           "softwares/fastq/hisat2.py",
           "softwares/bam/samtools.py",
           "softwares/bam/stringtie.py",
           "softwares/bam/featurecounts.py",
           "softwares/inhouse/r.py",
           "softwares/inhouse/bitk.py",
           "softwares/fasta/rnasamba.py",
           "softwares/fasta/gffread.py",
           "softwares/fastq/minimap2.py",
           "softwares/gtf/gffcompare.py",
           "utils.py"]

doc_url = "https://btrspg.github.io/pybiotools/"

git_url = "https://github.com/btrspg/pybiotools/tree/master/"

def custom_doc_links(name): return None
