# AUTOGENERATED! DO NOT EDIT! File to edit: u00_main_run.ipynb (unless otherwise specified).

__all__ = ['main']

# Cell

import defopt

from .cmdutils.cmdkallisto import kallisto_quant_merge

# Cell

def main():
    cmdlfs = [
        kallisto_quant_merge,
    ]
    defopt.run(cmdlfs)