# AUTOGENERATED! DO NOT EDIT! File to edit: utils.ipynb (unless otherwise specified).

__all__ = ['load_config', 'config']

# Cell

def load_config(*configs):
    config = configparser.ConfigParser()
    config.read(configs)
    return config

def config(new_config):
    return load_config(pkg_resources.resource_filename('pybiotools','default.ini'),new_config)