# AUTOGENERATED! DO NOT EDIT! File to edit: 09_bitk.ipynb (unless otherwise specified).

__all__ = ['Bitk']

# Cell


from ..base import Base, modify_cmd


# Cell


class Bitk(Base):
    def __init__(self, software, fd):
        super(Bitk, self).__init__(software)
        self._default = fd
        if '/' in software:
            bin = os.path.dirname(software) + '/'
        else:
            bin = ''
        self._dedim = bin + 'dedim.py'
        self._fc_rename = bin + 'fc_rename.py'



    def cmd_version(self):
        '''
        :return:
        '''
        return 'echo {repr} ;{software} --version'.format(
            repr=self.__repr__(),
            software=self._dedim
        )

    @modify_cmd
    def cmd_dedim(self, count,prefix,clinical,size,style,title):
        '''
        '''
        return r'''
{software}  {count} {prefix} \
            --annotation {clinical} \
            --size {size} \
            --style {style} \
            -t {title} \
            {dedim_para}
        '''.format(
            software=self._dedim,
            dedim_para=self._default['dedim'],
            **locals()
        )

    @modify_cmd
    def cmd_fc_rename(self, fc,clinical,prefix,sample_title,bam_title,count_title):
        '''
        '''
        return r'''
{software} {fc} {clinical} {prefix} \
        -s {sample_title} \
        -b {bam_title} \
        -c {count_title}
        '''.format(
            software=self._fc_rename,
            **locals()
        )

    def __repr__(self):
        return 'inhouse python package:' + self._software

    def __str__(self):
        return '''
In-house python package, https://github.com/btrspg/bitk.git
        '''