name: release
on:
  release:
    types:
      - published
      - prereleased
      - released
jobs:
  release_to_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install nbdev jupyter twine
        pip install -e .
    - name: generate config
      run: |
        echo -e "[pypi]\nusername=btrspg\npassword=${{secrets.pypipasswd}}" > ~/.pypirc

    - name: make release
      run: |
        make release
